### PR TITLE
Add NTP lib.

### PR DESCRIPTION
**Pull request by philcrump**
An implementation of SNTP, derived from the Mk3-Firmware implementation. Could be added to a post-wifi-connect hook once well-tested.

Changes from Mk3-Firmware:
- Catch exception when DNS lookup fails.
- Handle KoD response.
- Add multiple host failover.

TODO before merging:
- [x] Run/Test on Mk3 Badge / Firmware.
- [x] Run/Test on Mk4 Badge / Firmware.
- ~~[ ] Test using IP Address strings with Mk4 Firmware, see line 13.~~
- [x] Use onsite NTP server as primary (need hostname/IP from NOC).
- [x] Use NTP Pool vendor zone as secondaries (https://www.ntppool.org/vendors.html)

### CODE REVIEW

**Comment by thibault-ml** [comment]
Glad you were able to use my code from last year! Thanks for the changes :-)

**Comment by marekventur** [comment]
Thanks! Code looks good to me. Please give me some time to test it on the new badge and write some tests. I'm currently in the middle of some big changes, so it might take a few hours.

**Comment by philcrump** [comment]
I'll be on site from wednesday afternoon, I'm happy to progress it myself if I can get my hands on a Mk4 then.

**Comment by marekventur** [comment]
@philcrump https://github.com/emfcamp/Mk4-Apps/pull/17 - all tested and working, I only had to do a few minor changes. Let me know if you're happy with it and I'll get it merged.

**Comment by marekventur** [comment]
first bit is merged, keeping this open for the additional points mentioned on here and on PR #17

**Comment by philcrump** [comment]
NTP Vendor Zone approved: [0-3].emfbadge.pool.ntp.org

**Comment by marekventur** [comment]
@philcrump do you need to send another PR for that? I have no idea how NTP works.

**Comment by marekventur** [comment]
perfect! no rush, seems to work fine so far. Btw, would you be happy to help with reviewing apps/PRs during the event? We're currently looking for volunteers to help us keep an eye on submissions.

**Comment by marekventur** [comment]
There seems to be an ntp server allocated already: https://wiki.emfcamp.org/wiki/Network#Wireless

**Comment by philcrump** [comment]
I've not been able to test this on the badge, but as it was previously approved and I'm only changing the hosts, I'm content for it to be merged and closed.

**Comment by thibault-ml** [comment]
LGTM 👍

**Pull request merged**
